spring:
  application:
    name: eureka-service
server:
  port: 1025
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:1025/eureka
  server:
    enable-self-preservation: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always