spring:
  application:
    name: gateway
  cloud:
    gateway:
      api-prefix: /gateway
      routes:
        - id: order_router
          uri: lb://order-service
          predicates:
            - Path=/order/**
        - id: product_router
          uri: lb://order-service
          predicates:
            - Path=/product/**
server:
  port: 8086
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:1025/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  server:
    servlet:
      context-path: /gateway
