spring:
  application:
    name: zipkin-server
server:
  port: 8084
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 20
  client:
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://localhost:1025/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  #防止zipkin服务端启动报错
  metrics:
    web:
      server:
        auto-time-requests: false
zipkin:
  collector:
    kafka:
      bootstrap-servers: localhost:9092
      zookeeper: localhost:2181
      topic: zipkin
  storage:
    type: mysql
    mysql:
      host: localhost
      port: 3306
      username: root
      password: 15671601816
      useSsl: false
      db: zipkin